version: '3.4'
services:
  database:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: rajneesh
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb
    deploy: 


  wordpress:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    deploy:
      replicas: 2
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: rajneesh
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_storage:/var/www/html
volumes:
  wp_storage: 
  mysql_storage: 
